### ISSUE TITLE
Praise and Question

### ISSUE THREAD

**Issue by facultymatt** [jsoverson/grunt-strip#2]
Hello @jsoverson, awesome plugin! What a much cleaner solution then just adding some "safe console log" scripts.

I have a question... will this task still work if run on a minified js file? Or, should we be using the original? 

Not really an issue, but I thought posting here would be a valuable resource for anyone else looking to answer this. 

Thanks, 
-Matt

**Comment by jsoverson** [comment]
Thanks for the comments. This will still work on a minified file as long as the minification doesn't mangle the names of the nodes you are trying to strip.

It is probably best to run it on pre-minified files, though. I consider minification the last-step compilation of JS and anything after that point probably shouldn't expect to touch the structure of the generated javascript.
