### ISSUE TITLE
Latest release not compatible with latest stable release of Grunt?

### ISSUE THREAD

**Issue by HamishCharles** [jsoverson/grunt-strip#3]
I get the following error:-
Running "strip:main" (strip) task
c:\users\Hamish\webroot\portal\build\node_modules\grunt-requirejs\node_modules\q
\q.js:1327
                throw error;
                      ^
TypeError: Object #<Object> has no method 'options'

I get this whether I use the Options or not.

I am running grunt v0.3.17 (the stable release). I notice your latest release is for grunt 0.4.0rc7. Is this the reason for the error?

Hamish

**Comment by jsoverson** [comment]
Yes, it is, I should have published with a tag so that it wouldn't be installed unless requested, sorry. I'm hoping grunt 0.4.0 will drop within the next several days so this will be the new version soon anyway.
